# Generated by Django 3.2.8 on 2021-10-20 01:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='%Y/%m/%d')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{3,4}-?\\d{4}$', message='휴대폰 번호를 입력해주세요.')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
